# https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/publishing-docker-images
name: github-docker
on: 
  push:
    branches:
      - main



env:      
  DOCKER_PASSWORD:   ${{  secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME:   lskatz
  CI_PROJECT_NAME:   container-test
  github_repository: lskatz/container-test
  tag: fake-tag

jobs:
  push_to_registry:
    name: Push Docker image to multiple registries v2
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Prepare env
        id:   prep
        run: |
          DOCKER_IMAGE=${{ env.github_repository }}
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${GITHUB_SHA}"
          echo ::set-output name=tags::${TAGS}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lskatz
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=lskatz/container-test
          cache-to:   type=registry,ref=lskatz/container-test
          tags: ${{ steps.prep.outputs.tags }}
            
